#include<time.h>
#include<stdio.h>
/* Template for creating problem solutions */

int blurb(void)
{
    const char * blurb = R"(
    Each new term in the Fibonacci sequence is generated by adding the previous
    two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not
    exceed four million, find the sum of the even-valued terms.
    )";
    printf("%s \n", blurb);
}

int sum_even_fibonacci_numbers(int upper_bound, int previous, int next)
{
    int fibonacci_sum = 0;
    if (previous > upper_bound) {
        return 0;
    } else {
        if (previous % 2 == 0) {
            fibonacci_sum = previous;
        }
        return  fibonacci_sum + sum_even_fibonacci_numbers(upper_bound,
                                                           next,
                                                           previous + next);
    }
}

int problem_002(int upper_bound)
{
    return sum_even_fibonacci_numbers(upper_bound, 0, 1);
}

int main(void)
{
    blurb();
    clock_t begin = clock();
    int result = problem_002(4000000);
    clock_t end = clock();
    float elapsed_secs = ((float)end - (float)begin) / 1000000.0F;
    printf("Result: %d \n", result);
    printf("Completed in: %f seconds. \n", elapsed_secs);
    return 0;
}
