#!/usr/bin/env python3
import time
import math

def blurb():
    print("""
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle        Tn=n(n+1)/2         1, 3, 6, 10, 15, ...
Pentagonal      Pn=n(3n−1)/2        1, 5, 12, 22, 35, ...
Hexagonal       Hn=n(2n−1)      1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
    """)

def is_pentagonal(x):
    pentagonal_test = (math.sqrt((24 * x) + 1) + 1) / 6
    if pentagonal_test % 1 == 0: return True
    return False

def is_hexagonal(x):
    hexagonal_test = (math.sqrt((8 * x) + 1) + 1) / 4
    if hexagonal_test % 1 == 0: return True
    return False

def find_tri_pen_hex_numbers():
    '''
    hexagonal / pentagonal tests from wikipedia
    '''
    triangle_number = lambda x: 0.5 * x * (x + 1)
    triangle_numbers = [triangle_number(x) for x in range(2,1000000)]
    results = []
    for number in triangle_numbers:
        if is_pentagonal(number):
            if is_hexagonal(number):
                results.append(int(number))
    # Return last item in list
    return results[:0:-1][0]

def main():
    blurb()
    start = time.time()
    RESULT = find_tri_pen_hex_numbers()
    end   = time.time() - start
    print("Result: %s"      % RESULT)
    print("Completed in %s" % end)

if __name__ == '__main__':
    main()
